package com.rskt.spring.cloud.domain.mapper;

import com.rskt.spring.cloud.domain.TblUser;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:17:16 CST 2018
     */
    @Delete({
        "delete from tbl_user",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:17:16 CST 2018
     */
    @Insert({
        "insert into tbl_user (user_id, login_id, ",
        "user_name, email, ",
        "passwd, user_type, ",
        "delete_flg)",
        "values (#{userId,jdbcType=VARCHAR}, #{loginId,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{passwd,jdbcType=VARCHAR}, #{userType,jdbcType=VARCHAR}, ",
        "#{deleteFlg,jdbcType=CHAR})"
    })
    int insert(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:17:16 CST 2018
     */
    @Select({
        "select",
        "user_id, login_id, user_name, email, passwd, user_type, delete_flg",
        "from tbl_user",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="login_id", property="loginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="passwd", property="passwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_type", property="userType", jdbcType=JdbcType.VARCHAR),
        @Result(column="delete_flg", property="deleteFlg", jdbcType=JdbcType.CHAR)
    })
    TblUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:17:16 CST 2018
     */
    @Select({
        "select",
        "user_id, login_id, user_name, email, passwd, user_type, delete_flg",
        "from tbl_user",
        "order by user_id asc"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="login_id", property="loginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="passwd", property="passwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_type", property="userType", jdbcType=JdbcType.VARCHAR),
        @Result(column="delete_flg", property="deleteFlg", jdbcType=JdbcType.CHAR)
    })
    List<TblUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:17:16 CST 2018
     */
    @Update({
        "update tbl_user",
        "set login_id = #{loginId,jdbcType=VARCHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "passwd = #{passwd,jdbcType=VARCHAR},",
          "user_type = #{userType,jdbcType=VARCHAR},",
          "delete_flg = #{deleteFlg,jdbcType=CHAR}",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TblUser record);
}