package com.rskt.spring.cloud.domain.mapper;

import com.rskt.spring.cloud.domain.TblUser;
import java.util.List;

public interface TblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:53:20 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:53:20 CST 2018
     */
    int insert(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:53:20 CST 2018
     */
    TblUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:53:20 CST 2018
     */
    List<TblUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Fri Sep 21 16:53:20 CST 2018
     */
    int updateByPrimaryKey(TblUser record);
}